"""remove_blob_urls

Revision ID: 5ff5c74515fd
Revises: 
Create Date: 2026-02-20 12:05:18.831940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ff5c74515fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_chunks_id'), table_name='lesson_chunks')
    op.drop_index(op.f('ix_lesson_chunks_lesson_id'), table_name='lesson_chunks')
    op.drop_table('lesson_chunks')
    op.alter_column('courses', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('lessons', sa.Column('video_path', sa.Text(), nullable=True))
    op.add_column('lessons', sa.Column('pdf_path', sa.Text(), nullable=True))
    op.alter_column('lessons', 'transcript_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_column('lessons', 'pdf_url')
    op.drop_column('lessons', 'recording_blob_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('recording_blob_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('lessons', sa.Column('pdf_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('lessons', 'transcript_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_column('lessons', 'pdf_path')
    op.drop_column('lessons', 'video_path')
    op.alter_column('courses', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_table('lesson_chunks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chunk_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('lesson_chunks_lesson_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lesson_chunks_pkey')),
    sa.UniqueConstraint('chunk_id', name=op.f('lesson_chunks_chunk_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_lesson_chunks_lesson_id'), 'lesson_chunks', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_chunks_id'), 'lesson_chunks', ['id'], unique=False)
    # ### end Alembic commands ###
